export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const PATIENTS_LIST = 'PATIENTS_LIST';
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';

export const DIAGNOSES = 'DIAGNOSES';
export const DIAGNOSES_SUCCESS = 'DIAGNOSES_SUCCESS';
export const DIAGNOSES_ERROR = 'DIAGNOSES_ERROR';

export const DIAGNOSES_GET = 'DIAGNOSES_GET';
export const DIAGNOSES_GET_SUCCESS = 'DIAGNOSES_GET_SUCCESS';
export const DIAGNOSES_GET_ERROR = 'DIAGNOSES_GET_ERROR';

export const DIAGNOSES_CREATE = 'DIAGNOSES_CREATE';
export const DIAGNOSES_CREATE_SUCCESS = 'DIAGNOSES_CREATE_SUCCESS';
export const DIAGNOSES_CREATE_ERROR = 'DIAGNOSES_CREATE_ERROR';

export const DIAGNOSES_UPDATE = 'DIAGNOSES_UPDATE';
export const DIAGNOSES_UPDATE_SUCCESS = 'DIAGNOSES_UPDATE_SUCCESS';
export const DIAGNOSES_UPDATE_ERROR = 'DIAGNOSES_UPDATE_ERROR';

export const ALLERGIES = 'ALLERGIES';
export const ALLERGIES_SUCCESS = 'ALLERGIES_SUCCESS';
export const ALLERGIES_ERROR = 'ALLERGIES_ERROR';

export const ALLERGIES_GET = 'ALLERGIES_GET';
export const ALLERGIES_GET_SUCCESS = 'ALLERGIES_GET_SUCCESS';
export const ALLERGIES_GET_ERROR = 'ALLERGIES_GET_ERROR';

export const ALLERGIES_CREATE = 'ALLERGIES_CREATE';
export const ALLERGIES_CREATE_SUCCESS = 'ALLERGIES_CREATE_SUCCESS';
export const ALLERGIES_CREATE_ERROR = 'ALLERGIES_CREATE_ERROR';

export const ALLERGIES_UPDATE = 'ALLERGIES_UPDATE';
export const ALLERGIES_UPDATE_SUCCESS = 'ALLERGIES_UPDATE_SUCCESS';
export const ALLERGIES_UPDATE_ERROR = 'ALLERGIES_UPDATE_ERROR';

export const MEDICATIONS = 'MEDICATIONS';
export const MEDICATIONS_SUCCESS = 'MEDICATIONS_SUCCESS';
export const MEDICATIONS_ERROR = 'MEDICATIONS_ERROR';

export const MEDICATIONS_GET = 'MEDICATIONS_GET';
export const MEDICATIONS_GET_SUCCESS = 'MEDICATIONS_GET_SUCCESS';
export const MEDICATIONS_GET_ERROR = 'MEDICATIONS_GET_ERROR';

export const MEDICATIONS_CREATE = 'MEDICATIONS_CREATE';
export const MEDICATIONS_CREATE_SUCCESS = 'MEDICATIONS_CREATE_SUCCESS';
export const MEDICATIONS_CREATE_ERROR = 'MEDICATIONS_CREATE_ERROR';

export const MEDICATIONS_UPDATE = 'MEDICATIONS_UPDATE';
export const MEDICATIONS_UPDATE_SUCCESS = 'MEDICATIONS_UPDATE_SUCCESS';
export const MEDICATIONS_UPDATE_ERROR = 'MEDICATIONS_UPDATE_ERROR';

export const CONTACTS = 'CONTACTS';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

export const CONTACTS_GET = 'CONTACTS_GET';
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS';
export const CONTACTS_GET_ERROR = 'CONTACTS_GET_ERROR';

export const CONTACTS_CREATE = 'CONTACTS_CREATE';
export const CONTACTS_CREATE_SUCCESS = 'CONTACTS_CREATE_SUCCESS';
export const CONTACTS_CREATE_ERROR = 'CONTACTS_CREATE_ERROR';

export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_UPDATE_SUCCESS = 'CONTACTS_UPDATE_SUCCESS';
export const CONTACTS_UPDATE_ERROR = 'CONTACTS_UPDATE_ERROR';

export const ORDERS = 'ORDERS';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_ERROR = 'ORDERS_ERROR';

export const ORDERS_GET = 'ORDERS_GET';
export const ORDERS_GET_SUCCESS = 'ORDERS_GET_SUCCESS';
export const ORDERS_GET_ERROR = 'ORDERS_GET_ERROR';

export const ORDERS_CREATE = 'ORDERS_CREATE';
export const ORDERS_CREATE_SUCCESS = 'ORDERS_CREATE_SUCCESS';
export const ORDERS_CREATE_ERROR = 'ORDERS_CREATE_ERROR';

export const ORDERS_SUGGESTION = 'ORDERS_SUGGESTION';
export const ORDERS_SUGGESTION_SUCCESS = 'ORDERS_SUGGESTION_SUCCESS';
export const ORDERS_SUGGESTION_ERROR = 'ORDERS_SUGGESTION_ERROR';

export const REFERRALS = 'REFERRALS';
export const REFERRALS_SUCCESS = 'REFERRALS_SUCCESS';
export const REFERRALS_ERROR = 'REFERRALS_ERROR';

export const REFERRALS_GET = 'REFERRALS_GET';
export const REFERRALS_GET_SUCCESS = 'REFERRALS_GET_SUCCESS';
export const REFERRALS_GET_ERROR = 'REFERRALS_GET_ERROR';

export const REFERRALS_CREATE = 'REFERRALS_CREATE';
export const REFERRALS_CREATE_SUCCESS = 'REFERRALS_CREATE_SUCCESS';
export const REFERRALS_CREATE_ERROR = 'REFERRALS_CREATE_ERROR';

export const REFERRALS_UPDATE = 'REFERRALS_UPDATE';
export const REFERRALS_UPDATE_SUCCESS = 'REFERRALS_UPDATE_SUCCESS';
export const REFERRALS_UPDATE_ERROR = 'REFERRALS_UPDATE_ERROR';

export const PROCEDURES = 'PROCEDURES';
export const PROCEDURES_SUCCESS = 'PROCEDURES_SUCCESS';
export const PROCEDURES_ERROR = 'PROCEDURES_ERROR';

export const PROCEDURES_GET = 'PROCEDURES_GET';
export const PROCEDURES_GET_SUCCESS = 'PROCEDURES_GET_SUCCESS';
export const PROCEDURES_GET_ERROR = 'PROCEDURES_GET_ERROR';

export const PROCEDURES_CREATE = 'PROCEDURES_CREATE';
export const PROCEDURES_CREATE_SUCCESS = 'PROCEDURES_CREATE_SUCCESS';
export const PROCEDURES_CREATE_ERROR = 'PROCEDURES_CREATE_ERROR';

export const PROCEDURES_UPDATE = 'PROCEDURES_UPDATE';
export const PROCEDURES_UPDATE_SUCCESS = 'PROCEDURES_UPDATE_SUCCESS';
export const PROCEDURES_UPDATE_ERROR = 'PROCEDURES_UPDATE_ERROR';

export const DOCUMENTS = 'DOCUMENTS';
export const DOCUMENTS_SUCCESS = 'DOCUMENTS_SUCCESS';
export const DOCUMENTS_ERROR = 'DOCUMENTS_ERROR';

export const DOCUMENTS_FIND_REFERRAL = 'DOCUMENTS_FIND_REFERRAL';
export const DOCUMENTS_FIND_REFERRAL_SUCCESS = 'DOCUMENTS_FIND_REFERRAL_SUCCESS';
export const DOCUMENTS_FIND_REFERRAL_ERROR = 'DOCUMENTS_FIND_REFERRAL_ERROR';

export const DOCUMENTS_UPLOAD_REFERRAL = 'DOCUMENTS_UPLOAD_REFERRAL';
export const DOCUMENTS_UPLOAD_REFERRAL_SUCCESS = 'DOCUMENTS_UPLOAD_REFERRAL_SUCCESS';
export const DOCUMENTS_UPLOAD_REFERRAL_ERROR = 'DOCUMENTS_UPLOAD_REFERRAL_ERROR';

export const DOCUMENTS_FIND_DISCHARGE = 'DOCUMENTS_FIND_DISCHARGE';
export const DOCUMENTS_FIND_DISCHARGE_SUCCESS = 'DOCUMENTS_FIND_DISCHARGE_SUCCESS';
export const DOCUMENTS_FIND_DISCHARGE_ERROR = 'DOCUMENTS_FIND_DISCHARGE_ERROR';

export const DOCUMENTS_UPLOAD_DISCHARGE = 'DOCUMENTS_UPLOAD_DISCHARGE';
export const DOCUMENTS_UPLOAD_DISCHARGE_SUCCESS = 'DOCUMENTS_UPLOAD_DISCHARGE_SUCCESS';
export const DOCUMENTS_UPLOAD_DISCHARGE_ERROR = 'DOCUMENTS_UPLOAD_DISCHARGE_ERROR';

export const RESULTS = 'RESULTS';
export const RESULTS_SUCCESS = 'RESULTS_SUCCESS';
export const RESULTS_ERROR = 'RESULTS_ERROR';

export const RESULTS_GET = 'RESULTS_GET';
export const RESULTS_GET_SUCCESS = 'RESULTS_GET_SUCCESS';
export const RESULTS_GET_ERROR = 'RESULTS_GET_ERROR';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const CHART = 'CHART';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_ERROR = 'CHART_ERROR';

export const MESSAGE_SET = 'MESSAGE_SET';
export const MESSAGE_GET = 'MESSAGE_GET';

export const STUDIES = 'STUDIES';
export const STUDIES_SUCCESS = 'STUDIES_SUCCESS';
export const STUDIES_ERROR = 'STUDIES_ERROR';

export const SERIES_GET = 'SERIES_GET';
export const SERIES_GET_SUCCESS = 'SERIES_GET_SUCCESS';
export const SERIES_GET_ERROR = 'SERIES_GET_ERROR';

export const SERIES_DETAILS_GET = 'SERIES_DETAILS_GET';
export const SERIES_DETAILS_GET_SUCCESS = 'SERIES_DETAILS_GET_SUCCESS';
export const SERIES_DETAILS_GET_ERROR = 'SERIES_DETAILS_GET_ERROR';

export const INSTANCE_ID_GET = 'INSTANCE_ID_GET';
export const INSTANCE_ID_GET_SUCCESS = 'INSTANCE_ID_GET_SUCCESS';
export const INSTANCE_ID_GET_ERROR = 'INSTANCE_ID_GET_ERROR';

export const INSTANCE_GET = 'INSTANCE_GET';
export const INSTANCE_GET_SUCCESS = 'INSTANCE_GET_SUCCESS';
export const INSTANCE_GET_ERROR = 'INSTANCE_GET_ERROR';
