export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const PATIENTS_LIST = 'PATIENTS_LIST';
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const MESSAGE_SET = 'MESSAGE_SET';
export const MESSAGE_GET = 'MESSAGE_GET';
