export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const PATIENTS_LIST = 'PATIENTS_LIST';
export const PATIENTS_LIST_SUCCESS = 'PATIENTS_LIST_SUCCESS';
export const PATIENTS_LIST_ERROR = 'PATIENTS_LIST_ERROR';

export const DIAGNOSES = 'DIAGNOSES';
export const DIAGNOSES_SUCCESS = 'DIAGNOSES_SUCCESS';
export const DIAGNOSES_ERROR = 'DIAGNOSES_ERROR';

export const DIAGNOSES_GET = 'DIAGNOSES_GET';
export const DIAGNOSES_GET_SUCCESS = 'DIAGNOSES_GET_SUCCESS';
export const DIAGNOSES_GET_ERROR = 'DIAGNOSES_GET_ERROR';

export const DIAGNOSES_CREATE = 'DIAGNOSES_CREATE';
export const DIAGNOSES_CREATE_SUCCESS = 'DIAGNOSES_CREATE_SUCCESS';
export const DIAGNOSES_CREATE_ERROR = 'DIAGNOSES_CREATE_ERROR';

export const DIAGNOSES_UPDATE = 'DIAGNOSES_UPDATE';
export const DIAGNOSES_UPDATE_SUCCESS = 'DIAGNOSES_UPDATE_SUCCESS';
export const DIAGNOSES_UPDATE_ERROR = 'DIAGNOSES_UPDATE_ERROR';

export const ALLERGIES = 'ALLERGIES';
export const ALLERGIES_SUCCESS = 'ALLERGIES_SUCCESS';
export const ALLERGIES_ERROR = 'ALLERGIES_ERROR';

export const ALLERGIES_GET = 'ALLERGIES_GET';
export const ALLERGIES_GET_SUCCESS = 'ALLERGIES_GET_SUCCESS';
export const ALLERGIES_GET_ERROR = 'ALLERGIES_GET_ERROR';

export const ALLERGIES_CREATE = 'ALLERGIES_CREATE';
export const ALLERGIES_CREATE_SUCCESS = 'ALLERGIES_CREATE_SUCCESS';
export const ALLERGIES_CREATE_ERROR = 'ALLERGIES_CREATE_ERROR';

export const ALLERGIES_UPDATE = 'ALLERGIES_UPDATE';
export const ALLERGIES_UPDATE_SUCCESS = 'ALLERGIES_UPDATE_SUCCESS';
export const ALLERGIES_UPDATE_ERROR = 'ALLERGIES_UPDATE_ERROR';

export const MEDICATIONS = 'MEDICATIONS';
export const MEDICATIONS_SUCCESS = 'MEDICATIONS_SUCCESS';
export const MEDICATIONS_ERROR = 'MEDICATIONS_ERROR';

export const MEDICATIONS_GET = 'MEDICATIONS_GET';
export const MEDICATIONS_GET_SUCCESS = 'MEDICATIONS_GET_SUCCESS';
export const MEDICATIONS_GET_ERROR = 'MEDICATIONS_GET_ERROR';

export const MEDICATIONS_CREATE = 'MEDICATIONS_CREATE';
export const MEDICATIONS_CREATE_SUCCESS = 'MEDICATIONS_CREATE_SUCCESS';
export const MEDICATIONS_CREATE_ERROR = 'MEDICATIONS_CREATE_ERROR';

export const MEDICATIONS_UPDATE = 'MEDICATIONS_UPDATE';
export const MEDICATIONS_UPDATE_SUCCESS = 'MEDICATIONS_UPDATE_SUCCESS';
export const MEDICATIONS_UPDATE_ERROR = 'MEDICATIONS_UPDATE_ERROR';

export const CONTACTS = 'CONTACTS';
export const CONTACTS_SUCCESS = 'CONTACTS_SUCCESS';
export const CONTACTS_ERROR = 'CONTACTS_ERROR';

export const CONTACTS_GET = 'CONTACTS_GET';
export const CONTACTS_GET_SUCCESS = 'CONTACTS_GET_SUCCESS';
export const CONTACTS_GET_ERROR = 'CONTACTS_GET_ERROR';

export const CONTACTS_CREATE = 'CONTACTS_CREATE';
export const CONTACTS_CREATE_SUCCESS = 'CONTACTS_CREATE_SUCCESS';
export const CONTACTS_CREATE_ERROR = 'CONTACTS_CREATE_ERROR';

export const CONTACTS_UPDATE = 'CONTACTS_UPDATE';
export const CONTACTS_UPDATE_SUCCESS = 'CONTACTS_UPDATE_SUCCESS';
export const CONTACTS_UPDATE_ERROR = 'CONTACTS_UPDATE_ERROR';

export const RESULTS = 'RESULTS';
export const RESULTS_SUCCESS = 'RESULTS_SUCCESS';
export const RESULTS_ERROR = 'RESULTS_ERROR';

export const RESULTS_GET = 'RESULTS_GET';
export const RESULTS_GET_SUCCESS = 'RESULTS_GET_SUCCESS';
export const RESULTS_GET_ERROR = 'RESULTS_GET_ERROR';

export const SEARCH = 'SEARCH';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const CHART = 'CHART';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const CHART_ERROR = 'CHART_ERROR';

export const MESSAGE_SET = 'MESSAGE_SET';
export const MESSAGE_GET = 'MESSAGE_GET';
