sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

before_script:
  - npm install -g webpack

install:
  - npm install
  - bower install

script:
  - npm test
  - npm run build

notifications:
  email:
    on_failure: change
    on_success: change
