sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g webpack
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
  - npm run build

branches:
  only:
    - develop

notifications:
  email:
    on_failure: change
    on_success: change
