sudo: required
dist: trusty

language: node_js

cache:
  directories:
    - node_modules
    - bower_components

node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g codecov
  - npm install -g webpack
  - npm install -g bower
  - npm install
  - bower install

script:
  - npm test
#  - npm run build
  - npm run codecov

#after_success:
#  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
#  - npm run codecov

branches:
  only:
    - develop

notifications:
  email:
    on_failure: change
    on_success: change
